[project]
name = "grocerystore"
version = "0.1.0"
description = ""
authors = [
    {name = "saparbegov_01",email = "zidan_2002@mail.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic (>=1.18.4,<2.0.0)",
    "fastapi (>=0.136.1,<0.137.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
